{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Optimization"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sn\n",
    "import platypus"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import dike_model_function\n",
    "import dike_model_optimization\n",
    "import dike_model_simulation\n",
    "import problem_formulation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Logger EMA (DEBUG)>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from ema_workbench import Policy, perform_experiments\n",
    "from ema_workbench import ema_logging, MultiprocessingEvaluator\n",
    "import ema_workbench\n",
    "ema_logging.log_to_stderr(ema_logging.INFO)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.1.4\n"
     ]
    }
   ],
   "source": [
    "print(ema_workbench.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[MainProcess/INFO] model initialized\n"
     ]
    }
   ],
   "source": [
    "model = problem_formulation.get_model_for_problem_formulation(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[MainProcess/INFO] pool started\n",
      "[MainProcess/INFO] generation 0: 0/250 nfe\n",
      "[MainProcess/INFO] performing 1 scenarios * 100 policies * 1 model(s) = 100 experiments\n",
      "[SpawnPoolWorker-1/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-8/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-6/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-2/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-3/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-5/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-4/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-7/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-9/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-10/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-11/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-12/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-13/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-14/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-15/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-16/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-17/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-18/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-19/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-20/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-21/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-22/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-23/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-24/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-25/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-26/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-27/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-28/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-29/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-30/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-31/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-32/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-33/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-34/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-35/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-36/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-37/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-38/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-39/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-40/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-41/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-42/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-43/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-44/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-45/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-46/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-47/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-48/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-49/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-50/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-51/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-52/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-53/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-54/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-55/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-56/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-57/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-58/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-59/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-60/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-61/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-62/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-63/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-64/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-65/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-66/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-67/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-68/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-69/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-70/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-71/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-72/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-73/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-74/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-75/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-76/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-77/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-78/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-79/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-80/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-81/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-82/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-83/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-84/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-85/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-86/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-87/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-88/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-89/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-90/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-91/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-92/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-93/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-94/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-95/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-96/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-97/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-98/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-99/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-100/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n"
     ]
    }
   ],
   "source": [
    "with MultiprocessingEvaluator(model) as evaluator:\n",
    "    results = evaluator.optimize(nfe=250, searchover='levers',\n",
    "                                 epsilons=[0.1,]*len(model.outcomes))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
